# Generated by Django 2.2.6 on 2019-12-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191213_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='armament',
        ),
    ]
