# Generated by Django 2.2.6 on 2019-12-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191213_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=False, upload_to='static/img/'),
        ),
    ]
